// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "../Calculadora.hpp"

// =====================
// Prueba para calculadora aditiva
// ---------------------

TEST_CASE("ex0", "[Calculadora aditiva]")
{
    Calculadora c(3,7);

    SECTION("Sumas de numeros reales") {
        REQUIRE(c.suma()==10);
    }

    SECTION("Multplicacion de numero reales") {
        REQUIRE(c.multiplica()==21);
    }
}

// =====================
// Prueba para calculadora sustractiva
// ---------------------

TEST_CASE("ex1", "[Calculadora sustractiva]")
{
    Calculadora c(3,7);

    SECTION("Resta de numeros reales") {
        REQUIRE(c.resta()==-4);
    }

    SECTION("Multplicacion de numero reales") {
        REQUIRE(c.divide()==3.0/7.0);
    }
}